# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realization',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
