# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0002_realization_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='realization',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='realization',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(to='songsapp.Tag'),
        ),
        migrations.AddField(
            model_name='realization',
            name='tags',
            field=models.ManyToManyField(to='songsapp.Tag'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='songsapp.Tag'),
        ),
    ]
