# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('songsapp', '0004_wonder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='songsapp.HierarchyItem')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='realization',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realization_set', to='songsapp.Song'),
        ),
        migrations.AddField(
            model_name='author',
            name='node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='songsapp.HierarchyItem'),
        ),
        migrations.AddField(
            model_name='song',
            name='node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='songsapp.HierarchyItem'),
        ),
    ]
