# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0006_auto_20171111_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchyitem',
            name='name',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
